---
#Install JDK from https://www.oracle.com/java/technologies/downloads/
- hosts: target

  tasks:
    - name: Get the JDK installer
      get_url:
       url: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
       dest: /tmp
       checksum: "sha256: b7d1c8b25d7d88a5716c20d93e724439638884540c05713091798e7a36aeee1a"

    - name: Install the JDK
      yum:
          name: /tmp/jdk-17_linux-x64_bin.rpm
          state: present
      become: yes

    - name: Remove JDK installer from tmp 
      file: 
       state: absent
       path: /tmp/jdk-17_linux-x64_bin.rpm
  
 
        


